config/routes.rb
BLocal::Application.routes.draw do
  
  resources :reviews do 
    resources :comments
  end

  root 'page#home'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
end

app/models/review.rb
class Review < ActiveRecord::Base

	has_many :comments, dependent: :destroy

	validates :place, presence: true
	validates :info, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
	@review = Review.find(params[:review_id])
	@comment = @review.comments.create(comment_params)
	redirect_to review_path(@review)
end

def destroy
	@review = Review.find(params[:review_id])
	@comment = @review.comments.find(params[:id])
	@comment.destroy
	redirect_to review_path(@review)
end

private
def comment_params
	params.require(:comment).permit(:commenter, :body)
end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def new
	@review = Review.new
end

def create
	@review = Review.new(review_params)
	
	if @review.save
	redirect_to @review
	else 
		render 'new'
	end
end

def update
	@review = Review.find(params[:id])

	if @review.update(review_params)
		redirect_to @review
	else
		render 'edit'
	end	
end

def show
  	@review = Review.find(params[:id])
end

def edit
	@review = Review.find(params[:id])
end

def index
	@review = Review.all
end

def destroy
	@review = Review.find(params[:id])
	@review.destroy

	redirect_to reviews_path
end


private
def review_params
	params.require(:review).permit(:place, :info)
	
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/comments/_comment.html.erb

<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.review, comment], 
									method: :delete,
									data: { confirm: 'Are you sure?' } %>

</p>

app/views/comments/_form.html.erb
<%= form_for([@review, @review.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BLocal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/home.html.erb
<h1>Home page for bLocal MVP</h1>
<br>
<h3>This home page will show all the reviews that have been written</h3>
<br>

<%= link_to 'Reviews', controller: 'reviews' %>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>

 <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited
      this review from being saved:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
 <% end %>

  <p>
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </p>
 
  <p>
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb

<h1>Listing Reviews</h1>
 
<table>
  <tr>
    <th>Place</th>
    <th>Review</th>
  </tr>
 
  <% @review.each do |review| %>
    <tr>
      <td><%= review.place %></td>
      <td><%= review.info %></td>
      <td><%= link_to "Show", review_path(review) %></td>
	<td><%= link_to "Edit", edit_review_path(review) %></td>
	<td><%= link_to "Destroy", review_path(review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to("New Review", new_review_path) %>
<%= link_to("Home Page", root_path) %> 

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p>
  <strong>Place:</strong>
  <%= @review.place %>
</p>
 
<p>
  <strong>Review:</strong>
  <%= @review.info %>
</p>

<h2>Comments</h2>
<%= render @review.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', reviews_path %>
<%= link_to "Edit", edit_review_path(@review) %>